apiVersion: v1
kind: ConfigMap
metadata:
  name: myshop-config
  namespace: myshop
data:
  # Service URLs (Kubernetes internal DNS)
  IDENTITYSERVER_URL: "http://identityserver-service"
  CATALOG_URL: "http://catalog-service"
  BASKET_URL: "http://basket-service"
  ORDER_URL: "http://order-service"
  DISCOUNT_URL: "http://discount-service"
  
  # MongoDB
  MONGO_CONNECTION: "mongodb://mongodb-service:27017"
  MONGO_DATABASE: "CatalogDb"
  
  # Redis
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  
  # Environment
  ASPNETCORE_ENVIRONMENT: "Production"