apiVersion: v1
kind: Secret
metadata:
  name: myshop-secrets
  namespace: myshop
type: Opaque
stringData:
  # SQL Server
  sa-password: "YourStrong@Pass123"
  
  # IdentityServer
  identity-client-secret: "myshopwebsitesecret"
  
  # Connection Strings
  identity-connection-string: "Server=mssql-service;Database=IdentityDb;User Id=sa;Password=YourStrong@Pass123;TrustServerCertificate=True;"
  order-connection-string: "Server=mssql-service;Database=OrderDb;User Id=sa;Password=YourStrong@Pass123;TrustServerCertificate=True;"
  discount-connection-string: "Server=mssql-service;Database=DiscountDb;User Id=sa;Password=YourStrong@Pass123;TrustServerCertificate=True;"