apiVersion: apps/v1
kind: Deployment
metadata:
  name: discount
  namespace: myshop
  labels:
    app: discount
spec:
  replicas: 2
  selector:
    matchLabels:
      app: discount
  template:
    metadata:
      labels:
        app: discount
    spec:
      containers:
        - name: discount
          image: tuncaguvenbilgi/myshop-dscount:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Development"
            - name: ASPNETCORE_URLS
              value: "http://+:80"
            - name: ConnectionStrings__DefaultConnection
              valueFrom:
                secretKeyRef:
                  name: myshop-secrets
                  key: discount-connection-string
            - name: IdentityServerUrl
              valueFrom:
                configMapKeyRef:
                  name: myshop-config
                  key: IDENTITYSERVER_URL
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: discount-service
  namespace: myshop
spec:
  selector:
    app: discount
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP